export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

//CONSTANTS -> reducer -> action (same old same old :) )

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL'
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET'
//FOR THE ORDER IN Profile
export const USER_ORDER_LIST_REQUEST = 'USER_ORDER_LIST_REQUEST'
export const USER_ORDER_LIST_SUCCESS = 'USER_ORDER_LIST_SUCCESS'
export const USER_ORDER_LIST_FAIL = 'USER_ORDER_LIST_FAIL'
//4:20 excellent explanation
