//Login Constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
//Registstration Constants
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
//User Details Constants
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'
//User Update Details Constants
export const USER_UPDATED_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATED_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATED_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATED_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const LIST_OF_USERS_REQUEST = 'LIST_OF_USERS_REQUEST'
export const LIST_OF_USERS_SUCCESS = 'LIST_OF_USERS_SUCCESS'
export const LIST_OF_USERS_FAIL = 'LIST_OF_USERS_FAIL'
export const LIST_OF_USERS_RESET = 'LIST_OF_USERS_RESET'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'
